public class ListaPalabras {

    public static String[] getSpanishTexts() {
        String[] spanishTexts = {
                "Hola",
                "Adiós",
                "Sí",
                "No",
                "Por favor",
                "Gracias",
                "De nada",
                "Buenos días",
                "Buenas tardes",
                "Buenas noches",
                "Hasta mañana",
                "Hasta luego",
                "¿Cómo estás?",
                "Estoy bien",
                "Estoy mal",
                "Me llamo",
                "Mucho gusto",
                "¿Qué tal?",
                "¿Qué pasa?",
                "¿Qué hora es?",
                "¿Dónde estás?",
                "Estoy aquí",
                "Estoy allí",
                "¿Por qué?",
                "Porque sí",
                "Porque no",
                "Lo siento",
                "No entiendo",
                "¿Hablas inglés?",
                "No hablo español",
                "¿Cómo se dice...?",
                "¿Qué significa...?",
                "Feliz cumpleaños",
                "Feliz Navidad",
                "Feliz Año Nuevo",
                "Te quiero",
                "Te amo",
                "Lo amo",
                "Lo odio",
                "Tengo hambre",
                "Tengo sed",
                "Estoy cansado",
                "Estoy emocionado",
                "Estoy aburrido",
                "Estoy feliz",
                "Estoy triste",
                "Estoy enojado",
                "Estoy confundido",
                "Estoy sorprendido",
                "Estoy asustado",
                "Estoy avergonzado",
                "Estoy celoso"
        };

        return spanishTexts;
    }

    public static String[] getEnglishTexts() {
        String[] englishTexts = {
                "Hello",
                "Goodbye",
                "Cheese",
                "Yes",
                "No",
                "Please",
                "Thank you",
                "You're welcome",
                "Good morning",
                "Good afternoon",
                "Good evening",
                "See you tomorrow",
                "See you later",
                "How are you?",
                "I'm fine",
                "I'm not good",
                "My name is",
                "Nice to meet you",
                "What's up?",
                "What's going on?",
                "What time is it?",
                "Where are you?",
                "I'm here",
                "I'm there",
                "Why?",
                "Because",
                "Not",
                "I'm sorry",
                "I don't understand",
                "Do you speak English?",
                "I don't speak Spanish",
                "How do you say...?",
                "What does...mean?",
                "Happy birthday",
                "Merry Christmas",
                "Happy New Year",
                "I love you",
                "I love him/her",
                "I love it",
                "I hate it",
                "I'm hungry",
                "I'm thirsty",
                "I'm tired",
                "I'm excited",
                "I'm bored",
                "I'm happy",
                "I'm sad",
                "I'm angry",
                "I'm confused",
                "I'm surprised",
                "I'm scared",
                "I'm embarrassed",
                "I'm jealous"
        };

        return englishTexts;
    }

    public static String[] getFrenchTexts() {

        String[] frenchTexts = {
                "Bonjour",
                "Au revoir",
                "Fromage",
                "Oui",
                "Non",
                "S'il vous plaît",
                "Merci",
                "De rien",
                "Bonjour (le matin)",
                "Bonjour (l'après-midi)",
                "Bonsoir",
                "À demain",
                "À plus tard",
                "Comment vas-tu ?",
                "Je vais bien",
                "Je ne vais pas bien",
                "Je m'appelle",
                "Enchanté(e)",
                "Quoi de neuf ?",
                "Qu'est-ce qui se passe ?",
                "Quelle heure est-il ?",
                "Où es-tu ?",
                "Je suis ici",
                "Je suis là-bas",
                "Pourquoi ?",
                "Parce que",
                "Pas",
                "Je suis désolé(e)",
                "Je ne comprends pas",
                "Parlez-vous anglais ?",
                "Je ne parle pas français",
                "Comment dit-on... ?",
                "Que signifie... ?",
                "Joyeux anniversaire",
                "Joyeux Noël",
                "Bonne année",
                "Je t'aime",
                "Je l'aime",
                "Je l'adore",
                "Je le déteste",
                "J'ai faim",
                "J'ai soif",
                "Je suis fatigué(e)",
                "Je suis excité(e)",
                "Je m'ennuie",
                "Je suis heureux(se)",
                "Je suis triste",
                "Je suis fâché(e)",
                "Je suis confus(e)",
                "Je suis surpris(e)",
                "J'ai peur",
                "Je suis embarrassé(e)",
                "Je suis jaloux(se)"
        };

        return frenchTexts;
    }
}
