public class ListaPalabras {

    public static String[] getSpanishTexts() {
        String[] spanishTexts = {
                "Hola",
                "Adiós",
                "Sí",
                "No",
                "Por favor",
                "Gracias",
                "De nada",
                "Buenos días",
                "Buenas tardes",
                "Buenas noches",
                "Hasta mañana",
                "Hasta luego",
                "¿Cómo estás?",
                "Estoy bien",
                "Estoy mal",
                "Me llamo",
                "Mucho gusto",
                "¿Qué tal?",
                "¿Qué pasa?",
                "¿Qué hora es?",
                "¿Dónde estás?",
                "Estoy aquí",
                "Estoy allí",
                "¿Por qué?",
                "Porque sí",
                "Porque no",
                "Lo siento",
                "No entiendo",
                "¿Hablas inglés?",
                "No hablo español",
                "¿Cómo se dice...?",
                "¿Qué significa...?",
                "Feliz cumpleaños",
                "Feliz Navidad",
                "Feliz Año Nuevo",
                "Te quiero",
                "Te amo",
                "Lo amo",
                "Lo odio",
                "Tengo hambre",
                "Tengo sed",
                "Estoy cansado",
                "Estoy emocionado",
                "Estoy aburrido",
                "Estoy feliz",
                "Estoy triste",
                "Estoy enojado",
                "Estoy confundido",
                "Estoy sorprendido",
                "Estoy asustado",
        };

        return spanishTexts;
    }

    public static String[] getEnglishTexts() {
        String[] englishTexts = {
                "Hello",
                "Goodbye",
                "Yes",
                "No",
                "Please",
                "Thank you",
                "You're welcome",
                "Good morning",
                "Good afternoon",
                "Good evening",
                "See you tomorrow",
                "See you later",
                "How are you?",
                "Im fine",
                "Im bad",
                "My name is",
                "Nice to meet you",
                "How are you?",
                "Whats up?",
                "What time is it?",
                "Where are you?",
                "Im here",
                "I'm there",
                "Why?",
                "Because",
                "Because I'm not",
                "I'm sorry",
                "I don't understand",
                "Do you speak English?",
                "No hablo español",
                "¿Cómo se dice...?",
                "What does it mean...?",
                "Feliz cumpleaños",
                "Feliz Navidad",
                "Happy New Year",
                "I love you",
                "I love you",
                "I love him",
                "I hate it",
                "I'm hungry",
                "I'm thirsty",
                "I'm tired",
                "I'm excited",
                "I'm bored",
                "I am happy",
                "I am sad",
                "I'm angry",
                "I'm confused",
                "I'm surprised",
                "I'm scared",

        };

        return englishTexts;
    }

    public static String[] getFrenchTexts() {

        String[] frenchTexts = {
                "Bonjour",
                "Au revoir",
                "Oui",
                "Non",
                "S'il vous plaît",
                "Merci",
                "De rien",
                "Bonjour",
                "Bonjour",
                "Bonsoir",
                "A demain",
                "A plus tard",
                "Comment allez-vous ?",
                "Je vais bien",
                "Je vais mal",
                "Je m'appelle",
                "Enchanté de vous rencontrer",
                "Comment ça va ?",
                "Quoi de neuf ?",
                "Quelle heure est-il ?",
                "Où es-tu ?",
                "Je suis ici.",
                "Je suis là.",
                "Pourquoi",
                "Parce que je le suis.",
                "Parce que je ne le suis pas",
                "Je suis désolé",
                "Je ne comprends pas.",
                "Vous parlez anglais ?",
                "Je ne parle pas espagnol",
                "Comment dites-vous... ?",
                "Que voulez-vous dire... ?",
                "Feliz cumpleaños",
                "Feliz Navidad",
                "Bonne année",
                "Je t'aime",
                "Je t'aime",
                "Je l'aime.",
                "Je déteste ça.",
                "J'ai faim",
                "J'ai soif",
                "Je suis fatigué.",
                "Je suis excité.",
                "Je m'ennuie",
                "Je suis heureux",
                "Je suis triste",
                "Je suis en colère",
                "Je suis confus",
                "Je suis surpris",
                "J'ai peur"
        };

        return frenchTexts;
    }
}
